### ISSUE TITLE
Provide example of Running Multiple Replications

### ISSUE THREAD

**Issue by CRG180** [ahbuss/DESpy#2]
Could you please provide a Github code example on how to run multiple replications?

**Comment by ahbuss** [comment]
To run multiple replications, simply wrap <tt>EventList.reset()</tt> and <tt>EventList.start_simulation()</tt> in a <tt>for</tt> loop for the desired number of replications.

To create confidence interval(s), add "outer" stats for each measure desired, resetting the "inner" stats between <tt>reset<></tt> and <tt>start_simulation</tt>. After <tt>start_simulation</tt> within the loop, add the mean (or whatever measure is desired> to the "outer" stat. After the replications are completed, there will be n independent observations of the desired metric.

The "outer" stats objects are always "tally" ones, even if the "inner" stats objects are time-varying.

An example of running the EntityServer model for multiple replications is in [RunEntityServerMultipleReps](https://github.com/ahbuss/DESpy/blob/master/simkit/examples/run/RunEntityServerMultipleReps.py)

Here, there are 95% confidence intervals estimated for delay in queue and number in queue.

**Comment by CRG180** [comment]
thanks
